// Application-level types (hand-authored)
// DB-generated types live in src/types/database.ts (generated by Supabase CLI)

export type TicketStatus =
  | 'QUEUED'
  | 'ASSIGNED'
  | 'ACTIVE'
  | 'WAITING_ON_USER'
  | 'ESCALATED'
  | 'RESOLVED'
  | 'CLOSED'
  | 'REOPENED'
  | 'DEFERRED'

export type PriorityLabel =
  | 'Urgent'
  | 'Payment-Refund'
  | 'Booking Help'
  | 'General'

export type DeferredType = 'DEFERRED_TICKET' | 'CALLBACK_REQUEST'

export type AgentPresenceStatus = 'ONLINE' | 'OFFLINE' | 'INACTIVE'

export type UserRole = 'user' | 'agent' | 'super_admin'

export interface CreateTicketParams {
  categoryId:    string
  subject:       string
  description:   string
  priorityLabel: PriorityLabel
  bookingId?:    string
  propertyId?:   string
  deferredType?: DeferredType
  callbackPhone?: string
  callbackSlot?:  string
}

export interface SendMessageParams {
  ticketId:       string
  body:           string
  isInternalNote?: boolean
}

export interface ChatMessage {
  id:               string
  ticket_id:        string
  sender_id:        string
  sender_type:      'user' | 'agent' | 'system'
  body:             string
  is_internal_note: boolean
  read_at:          string | null
  created_at:       string
  message_attachments: MessageAttachment[]
}

export interface MessageAttachment {
  id:        string
  file_url:  string
  file_name: string
  file_type: string
  file_size: number
}

export interface TicketWithDetails {
  ticket_id:                   string
  ticket_number:               string
  subject:                     string
  description:                 string
  status:                      TicketStatus
  priority:                    number
  priority_label:              PriorityLabel
  user_id:                     string
  assigned_agent_id:           string | null
  category_id:                 string
  booking_id:                  string | null
  property_id:                 string | null
  parent_ticket_id:            string | null
  created_at:                  string
  updated_at:                  string | null
  queued_at:                   string
  assigned_at:                 string | null
  first_response_at:           string | null
  last_user_activity:          string | null
  escalated_at:                string | null
  escalated_by:                string | null
  resolved_at:                 string | null
  reopen_window_expires_at:    string | null
  closed_at:                   string | null
  rating:                      number | null
  rating_comment:              string | null
  complaint_categories:        { id: string; name: string } | null
  ticket_status_history:       StatusHistoryEntry[]
}

export interface StatusHistoryEntry {
  id:          string
  from_status: string | null
  to_status:   string
  note:        string | null
  created_at:  string
  changed_by:  string | null
}

// ---------------------------------------------------------------------------
// Video Submissions
// ---------------------------------------------------------------------------

export type VideoSubmissionStatus = 'pending' | 'reviewed'

export interface VideoSubmission {
  id:           string
  ticket_id:    string
  user_id:      string
  storage_path: string
  file_name:    string
  file_size:    number | null
  mime_type:    string | null
  status:       VideoSubmissionStatus
  reviewed_by:  string | null
  reviewed_at:  string | null
  created_at:   string
}

// ---------------------------------------------------------------------------
// KYC
// ---------------------------------------------------------------------------

export type KYCDocumentType = 'passport' | 'driving_license' | 'national_id' | 'other'
export type KYCStatus = 'pending' | 'approved' | 'rejected' | 'resubmit_required'

export interface KYCSubmission {
  id:                   string
  user_id:              string
  document_type:        KYCDocumentType
  document_front_path:  string
  document_back_path:   string | null
  selfie_path:          string | null
  status:               KYCStatus
  rejection_reason:     string | null
  reviewed_by:          string | null
  reviewed_at:          string | null
  created_at:           string
  updated_at:           string | null
}

export interface UserKYCStatus {
  user_id:              string
  is_verified:          boolean
  latest_submission_id: string | null
  last_verified_at:     string | null
  created_at:           string
}

export interface SubmitKYCParams {
  documentType:       KYCDocumentType
  documentFrontPath:  string
  documentBackPath?:  string
  selfiePath?:        string
}

// ---------------------------------------------------------------------------

export interface Notification {
  id:         string
  user_id:    string
  ticket_id:  string | null
  type:       'NEW_MESSAGE' | 'STATUS_CHANGE' | 'ASSIGNED' | 'ESCALATED' | 'SHIFT_END' | 'CALLBACK_DUE'
  payload:    Record<string, unknown>
  is_read:    boolean
  created_at: string
}
